name: Custom Jar
run-name: "Custom Jar - ${{ github.ref_name }}"

on:
  push:
    branches:
      - customjar/*
      
env:
  # access FULL_BRANCH var using: {{ env.FULL_BRANCH }}
  FULL_BRANCH: ${{ github.ref_name }}

jobs:

  custom_jar_job:
    name: Custom Jar Job
    runs-on: ubuntu-latest
    steps:

      - name: Get ACCDATA Ticket Number Step
        id: get-accdata
        uses: actions/github-script@v7
        with:
          # access this var using: ${{ steps.get-accdata.outputs.result }}
          script: |
            const fullBranch = "${{ env.FULL_BRANCH }}";
            const regex = /ACCDATA-(\d{1,9})/;
            const match = fullBranch.match(regex);
            if (match) {
                return match[0];
            } else {
                return null;
            }
          
      - name: Echo Variables Step
        run: |
          echo "FULL_BRANCH = ${{ env.FULL_BRANCH }}"
          echo "ACCDATA Ticket Number = ${{ steps.get-accdata.outputs.result }}"

      - name: Checkout the Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.FULL_BRANCH }}
