name: Custom Jar
run-name: Custom Jar

on:
  push:
    branches:
      - customjar/*

env:
  BRANCH_NAME: ${{github.ref_name}} 

jobs:
  
  echo_variables:
    name: Echo Variables
    runs-on: ubuntu-latest
    steps:
      - name: Echo Variables
        run: echo "BRANCH_NAME = ${{env.BRANCH_NAME}}"
             echo "subBranch = ${{steps.get-sub-branch.outputs.subBranch}}"
