name: Custom Jar
run-name: Custom Jar

on:
  push:
    branches:
      - customjar/*

env:
  BRANCH_NAME: ${{github.ref_name}} 

jobs:

  get_variables:
    name: Get Variables
    runs-on: ubuntu-latest
    steps:
      - name: Get Variables
        id: get-sub-branch
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const subBranch = ${{env.BRANCH_NAME}}.split('/')[1]
            core.setOutput('subBranch', subBranch)
  
  echo_variables:
    name: Echo Variables
    needs: get_variables
    runs-on: ubuntu-latest
    steps:
      - name: Echo Variables
        run: echo "BRANCH_NAME = ${{env.BRANCH_NAME}}"
             echo "subBranch = ${{steps.get-sub-branch.outputs.subBranch}}"
