name: Custom Jar

on:
  push:
    branches:
      - customjar/*

env:
  BRANCH_NAME: ${{github.ref_name}} 

jobs:
  
  echo_env_variables:
    name: Echo env Variables
    runs-on: ubuntu-latest
    steps:
      - name: Echo env Variables
        run: echo "The BRANCH_NAME is $BRANCH_NAME"
