name: Custom Jar
run-name: Custom Jar

on:
  push:
    branches:
      - customjar/*

env:
  BRANCH_NAME: ${{github.ref_name}} 

jobs:

  get_variables:
    name: Get Variables
    runs-on: ubuntu-latest
    steps:

      - name: Get Sub-Branch
        id: get-sub-branch
        uses: actions/github-script@v7.0.1
        with:
          script: return ${{env.BRANCH_NAME}}.split('/')[1]

      - name: Echo Variables
        run: echo "BRANCH_NAME = ${{env.BRANCH_NAME}}"
             echo "sub-branch = ${{steps.get-sub-branch.outputs.result}}"
