name: Custom Jar
run-name: "${{github.ref_name}}"

on:
  push:
    branches:
      - customjar/*
      
env:
  FULL_BRANCH: ${{github.ref_name}}

jobs:

  get_variables:
    name: Get Variables
    runs-on: ubuntu-latest
    steps:

      - name: Get Sub-Branch
        id: get-sub-branch
        uses: actions/github-script@v7.0.1
        with:
          script: return "${{env.FULL_BRANCH}}".split('/')[1]

  echo_variables:
    name: Echo Variables
    needs: get_variables
    runs-on: ubuntu-latest
    steps:      
      - name: Echo Variables
        run: |
          echo "FULL_BRANCH = ${{env.FULL_BRANCH}}"
          echo "SUB_BRANCH = ${{steps.get-sub-branch.outputs.result}}"
