name: Custom Jar
run-name: "${{github.ref_name}}"

on:
  push:
    branches:
      - customjar/*
      
env:
  FULL_BRANCH: ${{github.ref_name}}

jobs:

  get_variables:
    name: Get Variables
    runs-on: ubuntu-latest
    steps:

      - name: Get Sub-Branch
        id: get-sub-branch
        uses: actions/github-script@v7.0.1
        with:
          script: return "${{github.ref_name}}".split('/')[1]
          
      - name: Initialize Variables
        env:
          SUB_BRANCH: ${{steps.get-sub-branch.outputs.result}}
        run: |
          echo "FULL_BRANCH = $FULL_BRANCH"
          echo "SUB_BRANCH = $SUB_BRANCH"
          echo "result = ${{steps.get-sub-branch.outputs.result}}"

  echo_variables:
    name: Echo Variables
    needs: get_variables
    runs-on: ubuntu-latest
    steps:      
      - name: Echo Variables
        run: |
          echo "FULL_BRANCH = $FULL_BRANCH"
          echo "SUB_BRANCH = $SUB_BRANCH"
