name: Custom Jar
run-name: "${{github.ref_name}}"

on:
  push:
    branches:
      - customjar/*
      
env:
  FULL_BRANCH: ${{github.ref_name}}

jobs:

  get_variables:
    name: Get Variables
    runs-on: ubuntu-latest
    steps:

      - name: Get Sub-Branch
        id: get-sub-branch
        uses: actions/github-script@v7.0.1
        with:
          script: return "${{env.FULL_BRANCH}}".split('/')[1]
          
      - name: Initialize Variables
        run: |
          echo "SUB_BRANCH=${{steps.get-sub-branch.outputs.result}}" >> "$GITHUB_OUTPUT"
          echo "FULL_BRANCH = $FULL_BRANCH"
          echo "SUB_BRANCH = $SUB_BRANCH"
          echo "result = ${{steps.get-sub-branch.outputs.result}}"
